# Site settings
title: Arkhados
description: > # this means to ignore newlines until "baseurl:"
  Web site of Arkhados
baseurl: "/Arkhados/" # the subpath of your site, e.g. /blog/
url: "http://triplesnail.github.io" # the base hostname & protocol for your site
github_username:  TripleSnail

# Build settings
markdown: kramdown
