[General]
port = 12345
physicsTicksPerSecond = 60.0
defaultSyncFrequency = 0.05
gameMode = "TeamDeathmatch"

[GameModes]
[GameModes.Deathmatch]
killLimit = 25
respawnTime = 6.0

[GameModes.TeamDeathmatch]
killLimit = 25
respawnTime = 9.0
